# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Indepth Analysis
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 0 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_archived: yes
          plugin_followup_sections: user
