# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: People
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 0 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Contributors and sponsors
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.people.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 50
          plugin_people_size: 50
