# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Recent posts with descriptions and cover images
on:
  # Schedule updates (At 12:30AM Every Night)
  schedule: [{ cron: "30 0 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Recent posts with descriptions and cover images
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.posts.full.svg
          token: NOT_NEEDED
          base: ""
          plugin_posts: yes
          plugin_posts_user: datacrusade1999
          plugin_posts_source: dev.to
          plugin_posts_limit: 2
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes
