# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Stock Price
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 0 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Stock prices from Tesla
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stock.svg
          token: NOT_NEEDED
          base: ""
          plugin_stock: yes
          plugin_stock_token: ${{ secrets.STOCK_TOKEN }}
          plugin_stock_symbol: TSLA
