# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Twitter
on:
  # Schedule updates (At 12:30AM Every Night)
  schedule: [{ cron: "30 0 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
    push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Latest tweets including attachments
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.tweets.attachments.svg
          token: NOT_NEEDED
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_attachments: yes
          plugin_tweets_user: github
          plugin_tweets_limit: 1
